### ISSUE TITLE
Visual indication for "loading" on Search Page

### ISSUE THREAD

**Issue by FFrancieli** [tw-agendador/agendador#10]
**As a recruiter
I want to see a visual indication when the system is loading any information
So that I can know if I should wait the app finish some background work.**

## Acceptance Criteria

Given the user is on the Search Page
When they trigger a search
Then they should view a visual indication while the app loads all the information requested.

**Comment by adrdomeniconi** [comment]
Também acho isso fundamental, podemos implementar a solução que for adotada em todas as pesquisas que forem feita pelo sistema, e não apenas na busca de horários disponíveis.

**Comment by adrdomeniconi** [comment]
Started on August, 31

**Comment by twhrodrigu** [comment]
Started on August, 31
