### ISSUE TITLE
Check information source of TWer's office

### ISSUE THREAD

**Issue by adrdomeniconi** [tw-agendador/agendador#111]
Check from where the applications is currently getting the information about the TWer office: Home Office/Current Office or Working Office/Current Office.

It's important to notify the recruitment team about the result of the check.

**Comment by renanmartins** [comment]
We confirmed that the application is currently mapping the "Staffing / Working Office" from Jigsaw to the "Office" attribute in our system. 

Few examples (as of 10/01/2015):
Guilherme Dutra - Porto Alegre 
Patrick Sarnacke - Belo Horizonte 

Therefore:
Given that jigsaw information regarding "Staffing / Working Office" is correct and up to date, only consultants currently working on the selected office will be returned.

Observations:
- Consultants that are currently on short assignments will be returned. 
- Consultants that are currently on vacation will be returned.
The scenarios above may not be desired by Recruitment team. We need to confirm and create stories accordingly.
