### ISSUE TITLE
Define start and end time

### ISSUE THREAD

**Issue by FFrancieli** [tw-agendador/agendador#13]

**Comment by lucastfa** [comment]
Estão sendo aceitas horas iniciais posteriores a hora final. Ex: Data -> hoje 19:30 até 19:00, Role -> QA, Office -> BH. De alguma forma o Agendador retorna consultores para essa consulta.

**Comment by twhrodrigu** [comment]
Os campos de hora não estão funcionando de maneira esperada. Ao clicar no campo de data são exibidas várias opções de uma só vez, sem scroll down, e ao clicar fora das opções, o drop down não é minimizado. 
Passos para reproduzir: 
1. Estar na página inicial. 
2. Clicar em qualquer um dos campos de hora. 
Resultado: Todas as horas são apresentadas sem a barra de Scroll Down e não é possível esconder as opções a não ser que se escolha uma opções ou clicar em outro campo.
