### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by FFrancieli** [tw-agendador/agendador#19]
Atualmente, o Agendador está implantado no Heroku, que tem limitações quanto ao uso em seu plano gratuito.

A ideia é colocar o aplicativo no poarec01, talvez com o Dokku.

**Comment by felipead** [comment]
O Gregório definiu que iremos colocar o Agendador em produção no Heroku já para a próxima entrega.

**Comment by adrdomeniconi** [comment]
Task invalidade pois iremos fazer os deploys em máquinas disponibilizadas.

**Comment by patrickprado** [comment]
Begin 08-25-2015 (including Redis in Heroku instance)
