### ISSUE TITLE
Search by conduction level considering each type of interview

### ISSUE THREAD

**Issue by patrickprado** [tw-agendador/agendador#59]
**As a recruiter
I want to apply a filter by the conduction level of a TWer by each type of interview
So that I can find easily and faster the TWers who are able to conduct a specific type of interview**

## Notes
- The types of interviews are: "Technical/Pairing" and "P3".
- The levels of experience by each interview type are: "Leader", "Pair" and "All".
- The recruiter should be able to choose only one type of interview.
- The recruiter should be able to choose only one conduction level.
- Filter by type of interview is mandatory.  "Technical" is the default filter.
- Filter by level is mandatory.  "All" is the default filter.
- The fields should have labels.
- Exclude from the search people without interview experience. (People not allowed)

## Acceptance Criteria

Given the user is on the Search Page
When they indicate the type of the interview that will be conducted
Then they should be able to select one of the types ("Technical/Pairing" or "P3")

Given the user is on the Search Page
When they indicate the type of the interview that will be conducted
Then they should be able to select one of the types  ("Leader", "Pair" and "All")

Given the user is on the Search Page
When they completes all search criteria
And they confirm the action
And there are TWers  who match the search input 
Then they view a list with the correspondent result considering the type of interview and the conduction level
And the list presents TWers' name, picture and email

Given the user is on the Search Page
When they complete all search criteria
And they confirm the action
And there are no TWers  who match the search input 
Then they should view a message that no results were found.

## Wireframe
![Filters on the Search Page](http://i.imgur.com/s21EGdy.png)

**Comment by agdacjm** [comment]
Início: 21 de agosto

**Comment by twhrodrigu** [comment]
Foi encontrado um problema com a inicialização das horas nos componentes que já está sendo corrigido pelo time.
