### ISSUE TITLE
Add columns for other information

### ISSUE THREAD

**Issue by agdacjm** [tw-agendador/agendador#63]
## Narrative
**As a recruiter
I want to view main information about the TWers who match the search criteria
So that I can find easily and faster those who are aligned with the interview's requirements**

## Out of scope
- Apply filters to the search result #64

## Assumption
- Use the additional consultant attributes (issue #94) to populate the PeopleAvailable results table (issue #83)

## Notes
- Currently, recruiter views the following information: TWer's name, email and avatar. This story aims to insert others informations, which are: current project, role, grade and TW experience. These information should be imported from JigSaw.
- If any information is not available or doesn't exist, then the application should show a hyphen ( - ).

## Acceptance Criteria
Given the user is on "Find Available People"page
When they make a search
Then they view a list with the correspondent result
And the list presents TWer's information

## Wireframe
![Imgur](http://i.imgur.com/Bp3hXsg.png)

**Comment by twhrodrigu** [comment]
Existe um problema quando tentamos buscar os colaboradores no firefox. 
Ao preencher todos os filtros corretamente, o sistema retorna a mensagem de que não foi possível encontrar nenhum Thoughtworker. 
Entretanto, utilizando a mesma pesquisa no Chrome, foi possível visualizar o resultado com sucesso. 

Passos para reprodução:

1- Logar na aplicação. 
2- Preencher os filtros de forma que deveria retornar pelo menos um thoughtworker (preencher os dados de people info para que a busca funcione). 
3- Acionar o botão "Search".

Resultado:
A mensagem "No ThoughtWorker found" é exibida, mesmo quando os parâmetros são válidos e deveria retornar resultados.
