### ISSUE TITLE
Search TWer by Name or Email

### ISSUE THREAD

**Issue by adrdomeniconi** [tw-agendador/agendador#70]
**As a recruiter
I want to search a TWer by their name or e-mail 
so that I could view if they are allowed to be a Leader, a Pair or if they're not allowed to conduct a interview by each type.**

## Out of Scope
- Update the condition of the TWer to conduct a interview by each type.

## Notes
- The page that aims to display and update information about the condition of the TWer to conduct a interview is called "Update TWer Information". 
- The search can be made using the Name, E-mail or any substring.
- The list of results should present the following informations:
  - Name
  - Conduction level for a technical interview
  - Conduction level for a P3 interview

## Acceptance Criteria
Given the user is on the "Update TWer Information" page
When they search a TWer by their name or e-mail
And they confirm the action
If there are TWers  that match the search criteria
Then they should view a list of results of the TWer who match the search criteria

Given the user is on the "Update TWer Information" page
When they search a TWer by their name or e-mail
And they confirm the action
If there are no TWers  that match the search criteria
Then they should view a message that no results were found

## Wireframe
![Search TWer](http://i.imgur.com/nlz09XY.png)

**Comment by agdacjm** [comment]
Início: 06 de agosto
