### ISSUE TITLE
Update conduction level of a interviewer

### ISSUE THREAD

**Issue by adrdomeniconi** [tw-agendador/agendador#71]
**As a recruiter
I want to be able to update information about the conduction level of a interviewer
So that I can have a accurate search about TWers that are able to conduct an specific interview.**

## Notes
- The story #70 is an assumption for this one.
- The user is able to update ONLY the conduction level of a interview type. They cannot update other information about the user profile.
- The conduction level types are: Leader, Pair and Not Allowed.
- The interview types are: Technical/Pairing and P3.

## Acceptance Criteria
Given the user is on the "Update TWer Information" page
And they have a list of TWers
When they attempt to update the information regarding the conduction level of interview type
Then they view a message confirming that the information was updated successfully 
And the TWer profile should keep updated for further searches.

Given the user is on the "Update TWer Information" page
And they have a list of TWers
When they attempt to update the information regarding the conduction level of interview type
And an error occur during the transaction
Then they view a message that an error have occurred and the information was not updated. 

## Wireframe
![Imgur](http://i.imgur.com/EJ6k8B5.png)

**Comment by adrdomeniconi** [comment]
Interview types:

- Technical/Pairing
- P3

**Comment by patrickprado** [comment]
Start at 2015-08-17

**Comment by twhrodrigu** [comment]
Estória movida de volta para In Progress para que seja retirada a opção de Unset para o nível de condução de entrevista. 
Como sugestão, quando um consultant possuir um valor Nil para alguns dos níveis de condução de entrevista, sistema mostra como Not Allowed, ou, mostra em branco, mas sem que seja possível, após escolher um dos valores disponíveis, voltar para em branco. 

Pré-condição:
- Possuir pelo menos um Consultant com valor NIL para o nível de condução para pelo menos um dos tipos de entrevistas. 

Passos para reprodução:
1. Logar na aplicação. 
2. Acionar o link "People Info". 
3. Verificar um consultant que possui valor Nil como um de seus valores de nível de condução para alguma das entrevistas.
