### ISSUE TITLE
Add labels to form fields

### ISSUE THREAD

**Issue by adrdomeniconi** [tw-agendador/agendador#72]
**As a recruiter
I want to see labels over the form fields
So that I easily know what the field is about**

## Notes
- All the labels should be written in english. For example (Date, Time, Role, Office). 

## Acceptance Criteria

Given the user is on the Search Page
When they open the page 
Then they can see all the labels over the search fields

Given the user is on the Update Page
When they open the page 
Then they can see the label over the search field

**Comment by agdacjm** [comment]
Início: 25/ago
