### ISSUE TITLE
Filter list by other information

### ISSUE THREAD

**Issue by adrdomeniconi** [tw-agendador/agendador#89]
## Narrative
**As a recruiter
I want to apply filters by each information  in the search results
So that I can find easily and faster TWers who match interview's requirements**

## Notes
- The filter should be made using full text or substring.
- The filter should be applied to the fields: "name and email", "project", "role", "grade", "TW Experience", "Tech Skills".
- The filter for the field "TW Experience" should contain the following options:
  - "More than 0.5 year"
  - "More than 1 year"
 - "More than 2 years"
 - "More than 5 years"
- The filter for the field "Tech Skills" should contain the following options:
  - "More than 3"
  - "More than 4"
  - "5"
- All filters should contain an "all" option.

## Acceptance Criteria
Given the user view the search results on the "Find Available People" page
When they apply a filter on the  "Name and E-mail" column
And there are TWers who match the filter criteria
Then they view an updated list with the result related to the filter

Given the user view the search results on the "Find Available People" page
When they apply a filter on the  "Project" column
And there are TWers who match the filter criteria
Then they view an updated list with the result related to the filter

Given the user view the search results on the "Find Available People" page
When they apply a filter on the  "Role" column
And there are TWers who match the filter criteria
Then they view an updated list with the result related to the filter

Given the user view the search results on the "Find Available People" page
When they apply a filter on the  "Grade" column
And there are TWers who match the filter criteria
Then they view an updated list with the result related to the filter

Given the user view the search results on the "Find Available People" page
When they apply a filter on the  "TW Experience" column
And there are TWers who match the filter criteria
Then they view an updated list with the result related to the filter

Given the user view the search results on the "Find Available People" page
When they apply a filter on the  "Tech Skills" column
And there are TWers who match the filter criteria
Then they view an updated list with the result related to the filter

Given the user view the search results on the "Find Available People" page
When they select an "all" filter on a column
Then they view an updated list with no filter on that column

Given the user view the search results on the "Find Available People" page
When they apply a filter in the fields "name and email" and/or project and/or role and/or grade.
And there are no TWers who match the filter criteria
Then they view a message informing that no results were found

**Comment by patrickprado** [comment]
Started at 16-09-2015

**Comment by adrdomeniconi** [comment]
As we decided for performance reasons, the filter should be implemented on the server side.
