### ISSUE TITLE
 Filtrar por recrutadores que possam liderar entrevistas

### ISSUE THREAD

**Issue by FFrancieli** [tw-agendador/agendador#9]
Uma dificuldade para um recrutador é encontrar pares de entrevistadores onde um consiga liderar e o outro acompanhar. Atualmente o recrutador possui uma planilha contendo informações sobre entrevistadores que lideram e acompanham as entrevistas.

**Comment by felipead** [comment]
Block: definir com PO quais características definem que um consultor está apto a liderar uma entrevista. É um assunto complexo.
